version: "3.11.1"
services:
  app:
    container_name: django 
    build: 
      context: .
    command: ["sh/docker-entrypoint.sh"]
    ports:
      - 8000:8000
    env_file:
      - ./.env.example

  db:
    image: postgres
    container_name: db_pstg
    
    env_file:
    - ./.env.example 
    restart: always

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - 5438:5432

  