# Generated by Django 4.2.11 on 2024-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_links_options_alter_links_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='code',
            field=models.CharField(db_index=True, default='qwertyui', max_length=8, unique=True),
        ),
    ]
